"""add distributed_config to model_instances

Revision ID: a3f5c2e8b901
Revises: c477861f16be
Create Date: 2026-06-27 23:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a3f5c2e8b901'
down_revision: Union[str, None] = 'c477861f16be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'model_instances',
        sa.Column(
            'distributed_config',
            sqlmodel.sql.sqltypes.AutoString(length=2048),
            nullable=False,
            server_default='{}',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_instances', 'distributed_config')
    # ### end Alembic commands ###
