"""initial schema

Revision ID: c477861f16be
Revises: 
Create Date: 2026-06-27 22:19:47.156789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c477861f16be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('workers',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('labels', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('state', sa.Enum('NOT_READY', 'READY', 'UNREACHABLE', name='workerstate'), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_name'), 'workers', ['name'], unique=True)
    op.create_index(op.f('ix_workers_state'), 'workers', ['state'], unique=False)
    op.create_index(op.f('ix_workers_uuid'), 'workers', ['uuid'], unique=True)
    op.create_table('api_keys',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('allowed_model_names', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_access_token'), 'api_keys', ['access_token'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('models',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('source_repo', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('source_model_id', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('source_filename', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('backend', sa.Enum('LLAMA_CPP_STANDALONE', 'LLAMA_CPP_RPC', 'PRIMA_CPP', 'DATA_PARALLEL', name='modelbackend'), nullable=False),
    sa.Column('replicas', sa.Integer(), nullable=False),
    sa.Column('estimated_memory', sa.Integer(), nullable=False),
    sa.Column('required_instruction_sets', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('backend_parameters', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=True)
    op.create_index(op.f('ix_models_user_id'), 'models', ['user_id'], unique=False)
    op.create_table('worker_statuses',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('cpu_arch', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('cpu_model', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('cpu_allocated', sa.Integer(), nullable=False),
    sa.Column('cpu_utilization', sa.Float(), nullable=False),
    sa.Column('instruction_sets', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('numa_nodes', sa.Integer(), nullable=False),
    sa.Column('memory_total', sa.Integer(), nullable=False),
    sa.Column('memory_allocated', sa.Integer(), nullable=False),
    sa.Column('memory_available', sa.Integer(), nullable=False),
    sa.Column('swap_total', sa.Integer(), nullable=False),
    sa.Column('swap_used', sa.Integer(), nullable=False),
    sa.Column('disk_total', sa.Integer(), nullable=False),
    sa.Column('disk_available', sa.Integer(), nullable=False),
    sa.Column('network_bandwidth', sa.Integer(), nullable=False),
    sa.Column('os', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('kernel', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_statuses_worker_id'), 'worker_statuses', ['worker_id'], unique=True)
    op.create_table('model_files',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'DOWNLOADING', 'READY', 'ERROR', name='modelfilestate'), nullable=False),
    sa.Column('download_progress', sa.Float(), nullable=False),
    sa.Column('download_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_files_model_id'), 'model_files', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_files_state'), 'model_files', ['state'], unique=False)
    op.create_index(op.f('ix_model_files_worker_id'), 'model_files', ['worker_id'], unique=False)
    op.create_table('model_instances',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'ANALYZING', 'SCHEDULED', 'INITIALIZING', 'DOWNLOADING', 'STARTING', 'RUNNING', 'ERROR', 'UNREACHABLE', name='modelinstancestate'), nullable=False),
    sa.Column('allocated_cpu_cores', sa.Integer(), nullable=False),
    sa.Column('allocated_memory', sa.Integer(), nullable=False),
    sa.Column('rpc_worker_ids', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('service_port', sa.Integer(), nullable=True),
    sa.Column('backend_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('download_progress', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_instances_model_id'), 'model_instances', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_instances_name'), 'model_instances', ['name'], unique=False)
    op.create_index(op.f('ix_model_instances_state'), 'model_instances', ['state'], unique=False)
    op.create_index(op.f('ix_model_instances_worker_id'), 'model_instances', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_instances_worker_id'), table_name='model_instances')
    op.drop_index(op.f('ix_model_instances_state'), table_name='model_instances')
    op.drop_index(op.f('ix_model_instances_name'), table_name='model_instances')
    op.drop_index(op.f('ix_model_instances_model_id'), table_name='model_instances')
    op.drop_table('model_instances')
    op.drop_index(op.f('ix_model_files_worker_id'), table_name='model_files')
    op.drop_index(op.f('ix_model_files_state'), table_name='model_files')
    op.drop_index(op.f('ix_model_files_model_id'), table_name='model_files')
    op.drop_table('model_files')
    op.drop_index(op.f('ix_worker_statuses_worker_id'), table_name='worker_statuses')
    op.drop_table('worker_statuses')
    op.drop_index(op.f('ix_models_user_id'), table_name='models')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_access_token'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_workers_uuid'), table_name='workers')
    op.drop_index(op.f('ix_workers_state'), table_name='workers')
    op.drop_index(op.f('ix_workers_name'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
